--- a/Makefile	2019-05-19 08:41:18.081318140 +0200
+++ b/Makefile.new	2019-05-19 08:42:10.773429633 +0200
@@ -1,12 +1,9 @@
 rtk_hciattach:hciattach.c hciattach_rtk.o  
-	cc -o rtk_hciattach hciattach.c hciattach_rtk.o  
+	${CC} -o rtk_hciattach hciattach.c hciattach_rtk.o  
 
 hciattach_rtk.o:hciattach_rtk.c
-	cc -c hciattach_rtk.c
+	${CC} -c hciattach_rtk.c
 
 clean:
 	rm -f *.o  rtk_hciattach
 
-install:
-	mkdir -p /lib/firmware/rtl_bt
-	cp -p rtlbt_* /lib/firmware/rtl_bt/.
